### ISSUE TITLE
The resulting URL is incomplete

### ISSUE THREAD

**Issue by goxia** [anuraj/docschamps#1]
Hello Anuraj, 

The link I generated is like this, as if the end is missing symbol "/"
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-mount-and-customize?WT.mc_id=WDIT-MVP-4000544

Correct as follows：
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-mount-and-customize/?WT.mc_id=WDIT-MVP-4000544

**Comment by anuraj** [comment]
@goxia Is there any issue with the URL without a slash "/"? For me, both URLs are getting resolved properly.

**Comment by goxia** [comment]
Yes, it does not contain slash "/". maybe it won't affect the final statistics. thank you!

**Comment by anuraj** [comment]
Thank you. I am closing the issue.
